### ISSUE TITLE
v2 release checklist

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/protocol#50]
This ticket tracks a to-do list of small changes that need to be made before the v2 spec can be finalized. 

- [x] Diagrams: should be color coded to improve readability
- [x] DeltaGraph: delta limits should be specified here for clarity 
- [x] Hubs: Differential sync should be described with diagrams
- [x] Hubs: Key pair authentication should be specified 
- [x] Hubs: add sequence diagram to describe how gossip sync and differnential sync work 
- [x] Upgradeability: process for proposing protocol upgrades
- [x] Appendix: Rules for validating UserData
- [x] Appendix: gRPC API signatures for Hubs
- [x] Appendix: libp2p configuration details should be specified
- [x] Appendix: Specify the core team, and a public channel to communicate
- [x] Appendix: Link to longer form discussions that have informed the direction of the protocol
- [x] Appendix: Acknowledgements section should be added

**Comment by varunsrin** [comment]
add acknowledgements and proposals: https://github.com/farcasterxyz/protocol/pull/52
